### ISSUE TITLE
Add ability to set custom headers

### ISSUE THREAD

**Issue by deanishe** [domodwyer/mailyak#26]
Would it be possible to add a method for setting custom headers?

I'm thinking of things like `List-Unsubscribe` or `Precedence: bulk`, which are [helpful in avoiding your mails getting bounced](https://support.google.com/mail/answer/81126?hl=en).

Thanks.

**Comment by domodwyer** [comment]
Hi @deanishe 

Sounds like a good idea! I'll happily accept a PR for this :)

Dom

**Comment by domodwyer** [comment]
Hi @deanishe 

That's fair enough, I'll have a crack at it over the next day or too get back to you :) Thanks again for the suggestion!

Dom

**Comment by deanishe** [comment]
I'm more than happy to do it myself if you could clear up the above for me.

**Comment by domodwyer** [comment]
That would be cool!

The RFC states that q-encoding needs to be applied to any non-ASCII headers, so I think it is fine to q-encode all header key/values that are added using your proposed method. Because of this, I think only `AddHeader()` is required, unless you can see a use case for `AddHeaderRaw()`?

I think the interaction with existing methods that add headers (like `ReplyTo()`) should be kept as simple as possible - if the user calls `ReplyTo()` and sets the `Reply-To` header explicitly, include both - it's the least surprising behaviour and if it happens in real life, the issue would be easily noticed in the user's code.

However care needs to be taken to cover off header injection, say a user is running a web app that includes some user controlled value as a header, say a tracing ID from a cookie - a legitimate header might look like:

```
X-TRACING-ID: 4242424242424242
```

but as the value is user controlled, they could modify the cookie to set the value to `cats\r\nBcc: 1@spam.com,2@spam.com` resulting in:

```
X-TRACING-ID: cats
Bcc: 1@spam.com,2@spam.com
```

This is obviously bad - I think stripping newlines should suffice to prevent maliciously crafted input, but the documentation for `AddHeader()` _must_ mention that user-supplied header names should not be trusted. If someone accepts user input as headers (say via hidden form field) then they can overwrite legitimate values (like the `Content-Type` mime header) and do all sorts of nasty things.

Thanks again!

Dom

**Comment by deanishe** [comment]
> However care needs to be taken to cover off header injection

You mean run all header names and values through `trimRegex`, right?

**Comment by deanishe** [comment]
> unless you can see a use case for `AddHeaderRaw()`?

That suggestion was mostly based on my not knowing whether all headers need to be encoded or not. I certainly don't have a use for `AddHeaderRaw()`.

So, I'll just add `AddHeader()` at this time.

**Comment by domodwyer** [comment]
Hi @deanishe 

Yes `trimRegex` should do it! I agree we can leave `AddHeaderRaw()` out - I just wanted to make sure I wasn't missing something.

Again, thanks very much for taking the time to open a PR - it's much appreciated.

Dom

**Comment by deanishe** [comment]
^ Thar she blows. What do you think?
