### ISSUE TITLE
Commit c67f922 breaks plain text mails in most mail clients

### ISSUE THREAD

**Issue by Top-Ranger** [domodwyer/mailyak#63]
Hi,
unfortunately, the latest commit (c67f922) always adds an empty section ```Content-Type: text/html; charset=UTF-8``` to each plain text mail. This breaks the display of the mail on most mail clients since html-mail is default on most and only an empty mail is displayed in html view.

I'm not an expert in emails, but I *think* the way to fix this issue would be to not write a MIME boundary at all if the part is missing instead of writing an empty MIME part. However, since I do not have a GMail account I can not verify if https://github.com/domodwyer/mailyak/issues/61 would still be solved.

**Comment by domodwyer** [comment]
Ah I was afraid something like this would happen! **Thank you for reporting it!**

I had real trouble getting integration tests to deliver messages to gmail (likely because my test domain has DKIM/spf/etc) so couldn't reproduce the problem and kind of had to hope for the best. A bad strategy indeed.

I think not including the parts at all if they're empty makes sense - I'm happy to patch it this weekend or accept a PR if you fancy!

**Thanks again**,

Dom
