### ISSUE TITLE
Can I send e-mails directly?

### ISSUE THREAD

**Issue by ivanjaros** [domodwyer/mailyak#90]
Essentially all emails today are usually sent via some kind of smtp relay server(alias MTA), which is just STMP server that then connects to the addressee's SMTP server and actually deliver the email. I want to send emails directly. I would simply look up the dns MX records to find out the server information and connect to it directly. Can Yak do this? The only thing I would need to handle is to clean up multiple addressees(cc/bcc) and do it one by one(or per domain to be precise) but other than that I do not see technically why it should not work since what is happening with SMTP and MTA is the same thing, except authentication. It's still plain text smtp protocol underneath.

**Comment by domodwyer** [comment]
I'm sure it's possible, as MailYak implements the SMTP standard, so in theory it should be fine.

Practically speaking, I think you'll struggle with deliverability - DMARC is becoming more the norm (brilliant!) and source IP reputation still plays a big part. Effective email has increasingly become the domain of "trusted" entities.

I'm interested how this goes! I'm going to close this because it isn't a code issue, but please do report back on your progress regardless :+1:
